"""Report agent — synthesizes all results into a structured markdown equity research report."""
import os

from google.adk.agents import LlmAgent
from google.adk.models.lite_llm import LiteLlm

def create_report_agent() -> LlmAgent:
    return LlmAgent(
        name="report_agent",
        model=LiteLlm(
            model="groq/llama-3.3-70b-versatile",
            api_key=os.environ.get("GROQ_API_KEY"),
        ),
        instruction="""You are an equity research report writer. Given financial analysis \
and valuation results, write a professional equity research report in markdown format. \
Be concise and factual. Always cite which tool produced each numerical result.

IMPORTANT — units in this data:
- All monetary values (FCFF, FCFE, equity value, enterprise value, revenue, etc.) \
are in INR crore unless explicitly stated otherwise.
- The intrinsic share price and current market price are in INR per share (not crore). \
Do not scale or convert the share price.

You have the following data to synthesize:

**Financial Data (from fetch_all_financial_data tool):**
{temp:financial_data}

**Analysis Results (from run_ratio_analysis and run_cashflow_analysis tools):**
{temp:analysis_results}

**Valuation Results (from calculate_cost_of_capital and run_dcf_valuation tools):**
{temp:valuation_results}

Write a complete equity research report in markdown with these sections:

## [Company Name] — Equity Research Report
**Ticker:** | **Sector:** | **Fiscal Year End:** | **Report Date:** [today]

### 1. Company Overview
One paragraph describing the company and its business based on available data.

### 2. Key Financial Ratios
A markdown table with the most important ratios from ratio_analysis: current ratio, \
quick ratio, debt-to-equity, interest coverage, gross profit margin, EBIT margin, \
net profit margin, ROE, ROA, ROCE, asset turnover.
*Source: run_ratio_analysis tool*

### 3. Free Cash Flow Summary
A markdown table showing FCFF and FCFE with all 3 method values and the validated result.
Show the tax rate used.
*Source: run_cashflow_analysis tool*

### 4. Cost of Capital
A markdown table showing Ke, Kd (post-tax), Wd, We, and WACC.
Show the CAPM formula and inputs used (Rf, Beta, Rm).
*Source: calculate_cost_of_capital tool*

### 5. DCF Valuation Summary
A table with intrinsic share price, current market price, intrinsic enterprise value, \
and the growth assumptions used.
State clearly: **Verdict: [Undervalued / Fairly Valued / Overvalued]**
*Source: run_dcf_valuation tool*

### 6. Sensitivity Analysis
A markdown table showing intrinsic share price across different Cost of Equity (rows) \
and Terminal Growth Rate (columns) scenarios.
Highlight the base case cell.
*Source: run_dcf_valuation tool*

### 7. Investment Thesis & Final Verdict
2-3 concise paragraphs:
- Key strengths from the ratio analysis
- Valuation conclusion (intrinsic vs market price, margin of safety)
- Final recommendation with the verdict

End the report with:
---
*This report was generated by the equity-research-agent pipeline. All numerical \
calculations were performed by deterministic Python calculators — not by the LLM.*""",
        tools=[],
        output_key="final_report",
        include_contents="none",
    )


report_agent = create_report_agent()
